### ISSUE TITLE
How to use rwr-redux in javascript file?

### ISSUE THREAD

**Issue by Shaxmatist** [netguru/rwr-redux#9]
Like for RWR usage:

```
const element = $('#my-element');
RWR.renderComponent('customComponentName', {user_id: 1}, element);
```

**Comment by caspg** [comment]
You can't right now. But I'll update this  and release new version in the following week.

**Comment by caspg** [comment]
Hey @Shaxmatist. In latest v.0.4.0 version, you can use those methods in javascript. Here is list of methods available in public api: https://github.com/netguru/rwr-redux/blob/master/js/src/index.js#L19
